controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

car_index:
    path: /cars
    controller: App\Controller\CarsController::index

car_filter:
    path: /cars/filter
    controller: App\Controller\CarsController::filter

car_select:
    path: /cars/{id}
    controller: App\Controller\CarsController::show