controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

car_index:
    path: /cars
    controller: App\Controller\CarsController::index

car_select:
    path: /cars/{id}
    controller: App\Controller\CarsController::show

filters:
    path: /cars/_filterCars
    controller: App\Controller\CarsController::filter
    methods: GET
    requirements:
        minMileage: \d+
        maxMileage: \d+
        minReleaseYear: \d+
        maxReleaseYear: \d+
        minPrice: \d+
        maxPrice: \d+